### ISSUE TITLE
Support Diagnostics Tool consumed as a Java library

### ISSUE THREAD

**Issue by brunofarache** [elastic/support-diagnostics#485]
The Support Diagnostics Tool was designed to be used from the command line.

The objective of this issue is to also make it possible to consume this tool as a Java library.

Here are the changes to make that happen:

  - [x] Include `*.yaml` config files in released jars. Instead of distributing `*.yaml` separately from the jar file, it would be better to include them in the binary, this way, developers can just drop the jar in their projects without having to include a separate `config` folder in the classpath. (#488)
  - [x] `DiagnosticService#exec` should return `java.io.File` instead of `void`. This makes it easier for callers to know where the zip file was saved, otherwise they would need to list which files are present in the `outputDir` after the tool is finished. (#486)
  - [x] `DiagnosticService#exec` should throw `DiagnosticException` instead of logging and swallowing errors. `DiagnosticException` is a `RuntimeException` which makes harder for consumers be aware of errors and catch them properly. (#486)
  - [x] Close all `OutputStream` correctly to avoid memory leaks. I noticed some `OutputStream` instances are not being closed properly, while that's fine when running the tool in the command line, it may leak memory when being used many times by the same process. (#487)
  - [x] Archive should be always created, regardless if exceptions were thrown or not. (#493)
  - [x] Make sure the generated bundle contains `diagnostics.log`.
  - [x] Add option to always generate zip bundles and skip tars. (#494)
  - [x] Change license to ELv2. (#501)
  - [x] Publish to private Maven repo. We need to publish it somewhere in order to be added as a dependency to Java projects.

**Comment by CBlaisure** [comment]
Grooming notes:
Support Development to investigate github actions to deploy Maven automatically.

**Comment by shasts** [comment]
@brunofarache 
Just so you know, we have a few internal libraries published in our artifactory.

**Comment by pickypg** [comment]
I was able to get the person with Maven Central access to give me approval to create packages in the `co.elastic.*` `groupId`. They were on vacation until today. Now we wait for Sonatype.

https://issues.sonatype.org/browse/OSSRH-70696

They literally gave me permissions as I was posting this. I'll be trying it out soon.

**Comment by pickypg** [comment]
@brunofarache I was able to get this deployed to Maven Central: version 8.2.0. Gradle dependency:

```
dependencies {
  compile 'co.elastic.support:diagnostics:8.2.0'
}
```

**Comment by pickypg** [comment]
I was able to confirm this works locally with my own cluster:

```java
// ./src/main/java/org/elastic/Test.java
package org.elastic;

import co.elastic.support.Constants;
import co.elastic.support.diagnostics.DiagConfig;
import co.elastic.support.diagnostics.DiagnosticInputs;
import co.elastic.support.diagnostics.DiagnosticService;

import java.util.HashMap;

public class Test {

  private static DiagConfig createDiagConfig() {
    final var map = new HashMap<String, Integer>();

    map.put("connectTimeout", 60);
    map.put("requestTimeout", 60);
    map.put("socketTimeout", 120);
    map.put("maxTotalConn", 100);
    map.put("maxConnPerRoute", 10);

    final var logMap = new HashMap<String, Integer>();

    logMap.put("maxGcLogs", 0);
    logMap.put("maxLogs", 0);

    final var config = new HashMap<String, Object>();

    config.put("docker-container", new HashMap<String, String>());
    config.put("docker-container-ids", "");
    config.put("docker-executable-location", "");
    config.put("docker-global", new HashMap<String, String>());
    config.put("rest-config", map);
    config.put("call-retries", 3);
    config.put("pause-retries", 5000);
    config.put("log-settings", logMap);

    return new DiagConfig(config);
  }

  private static DiagnosticInputs createDiagnosticInputs() {
    final var inputs = new DiagnosticInputs();

    inputs.bypassDiagVerify = true;
    inputs.isSudo = true;
    inputs.archiveType = "zip";

    // inputs.outputDir = outputDir; // by not setting this, it writes in pwd
    inputs.scheme = "https";
    inputs.isSsl = true;
    inputs.host = "my-host";
    inputs.port = 9243;
    inputs.user = "elastic";
    inputs.password = "my_password";

    inputs.diagType = Constants.api;

    return inputs;
  }

  public static void main(String[] args) {
    System.out.println("Running diagnostic...");

    try {
      final var service = new DiagnosticService();

      service.exec(Test.createDiagnosticInputs(), Test.createDiagConfig());
    } catch (Exception e) {
      System.out.println("Failed to run diagnostic: " + e.getMessage());
      System.exit(1);
    }

    System.out.println("Done running diagnostic");
    System.exit(0);
  }

}
```

Gradle build

```groovy
// ./build.gradle
apply plugin: 'application'
apply plugin: 'java'

mainClassName = 'org.elastic.Test'

sourceCompatibility = 11
version = '1.0.0'

repositories {
  mavenCentral()
}

dependencies {
  compile 'co.elastic.support:diagnostics:8.2.0'
}
```

**Comment by brunofarache** [comment]
Awesome, thanks @pickypg. cc @gmarz
